name: Ejecutar Pruebas de Automatización CI

on:
  push:
    branches: [ main ] # Ejecutar cuando se sube código a la rama principal 'main'

jobs:
  pruebas_selenium:
    runs-on: ubuntu-latest # Servidor Linux virtual para las pruebas

    steps:
    - uses: actions/checkout@v4 # Descarga el código del repositorio
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Usar la versión más reciente de Python 3

    - name: Instalar Dependencias (Selenium 4.35.0 y Driver Manager)
      # Instalamos todo lo necesario para que tu script funcione en el servidor de GitHub
      run: pip install selenium webdriver-manager pytest

    - name: Ejecutar Pruebas
      # Pytest busca el archivo 'test_automatizacion.py' en la carpeta 'tests'
      # y ejecuta la prueba.
      run: pytest