name: Ejecutar Pruebas de Automatización CI
on:
  push:
    branches: [ main ]
jobs:
  pruebas_selenium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Instalar Dependencias (Selenium 4.35.0 y Driver Manager)
      run: pip install selenium webdriver-manager pytest
    - name: Limpiar el Cache de Python y archivos temporales
      run: |
        find . -type d -name "__pycache__" -exec rm -r {} +
        find . -type d -name "pruebas_temp" -exec rm -r {} +
    - name: Ejecutar Pruebas
      run: pytest